### ISSUE TITLE
v0.1.1 not working with Chrome Logger 4.0 

### ISSUE THREAD

**Issue by cj** [cookrn/chrome_logger#1]
Hi,

I install using `gem 'chrome_logger', github: 'cookrn/chrome_logger' , :require => 'chrome_logger/railtie` using `rails 3.2.13` and Chrome Version 27.0.1453.47 beta and I get the following error below.

```
Error in event handler for 'undefined': Unexpected end of input SyntaxError: Unexpected end of input
    at Object.parse (native)
    at _jsonDecode (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:162:21)
    at _decode (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:166:16)
    at _process (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:186:20)
    at _processQueue (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:147:13)
    at _run (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:215:9)
    at chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:225:13
    at miscellaneous_bindings:287:9
    at Event.dispatchToListener (event_bindings:356:21)
    at Event.dispatch_ (event_bindings:342:27) 
```

**Comment by cookrn** [comment]
Thanks for the report! I'll try it out as soon as I can.

In the meantime, can you provide more information as to what you're logging? ActiveRecord instances? POROs? Params?

Also, just out of curiosity, is there any reason you're fetching the gem directly from Github as opposed to Rubygems?

**Comment by cookrn** [comment]
Hi @cj -- a new version has been published to RubyGems with a fix from @grosser :: https://rubygems.org/gems/chrome_logger/versions/0.1.2

Can you try it out and let me know if that fixes your issue? Also, providing a Gist of your `Gemfile.lock` would be helpful as well.

**Comment by cookrn** [comment]
Please reopen if this is still an issue :smile:
